name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
